services:
  clickhouse:
    build:
      context: .
    ports:
      - "0:8123"
      - "0:9000"
    environment:
      CLICKHOUSE_DB: test_db
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./config:/etc/clickhouse-server/config.d
      - ./schema:/docker-entrypoint-initdb.d
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  clickhouse_data:
