services:
  clickhouse:
    build:
      context: .
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: mdxdb
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: ""
    volumes:
      - ./config:/etc/clickhouse-server/config.d
      - ./schema:/docker-entrypoint-initdb.d
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  clickhouse_data:
