version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server@sha256:3073efa0428c680834cf03dd2428fac3408a8a60310cd0613f51731eb25bcdb2
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./config:/etc/clickhouse-server/config.d
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DB=mdxdb
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
