services:
  clickhouse:
    build: .
    ports:
      - "58123:8123"  # HTTP port
      - "59000:9000"  # Native protocol port
    volumes:
      - ./config:/etc/clickhouse-server/config.d
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_DB: test_db
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_KEEPER_SERVER_ENABLED: 0
      CLICKHOUSE_DISTRIBUTED_DDL_ENABLED: 0
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - clickhouse_test
networks:
  clickhouse_test:
    name: ${COMPOSE_PROJECT_NAME}_default
