services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DB=mdxdb
    volumes:
      - type: bind
        source: ./docker/init-db.sh
        target: /docker-entrypoint-initdb.d/init-db.sh
        read_only: true
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 'http://localhost:8123/ping' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s
