services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "38123:38123"
      - "39000:39000"
    volumes:
      - ./config:/etc/clickhouse-server/config.d
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:38123/ping || exit 1
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 20s
