services:
  clickhouse:
    build:
      context: .
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: mdxdb
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: ""
    volumes:
      - ./config:/etc/clickhouse-server/config.d
      - ./schema:/docker-entrypoint-initdb.d
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping", "||", "exit", "1"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 5s

volumes:
  clickhouse_data:
