name = "mdxdb-server"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[build]
command = "pnpm run build"
watch_dir = "src"

[vars]
PROVIDER = "clickhouse"

[[kv_namespaces]]
binding = "MDXDB_KV"
id = "mdxdb-kv"

# Development environment
[env.development]
vars = { CLICKHOUSE_URL = "http://localhost:8123" }

# Staging environment
[env.staging]
vars = { CLICKHOUSE_URL = "https://clickhouse.staging.example" }

# Production environment
[env.production]
vars = { CLICKHOUSE_URL = "https://clickhouse.production.example" }

[miniflare]
kv_persist = true
