name: VSCode Extension

on:
  push:
    branches: [main]
    paths:
      - 'packages/vscode/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/vscode/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/vscode

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build workspace dependencies
        working-directory: /home/runner/work/mdxdb/mdxdb
        run: pnpm -w build

      - name: Build extension
        run: pnpm run compile

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Package Extension
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          npm install -g @vscode/vsce
          vsce package

      - name: Publish Extension
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
